### ISSUE TITLE
Please rename to remove -library

### ISSUE THREAD

**Issue by kristianmandrup** [PolymerElements/iron-jsonp-library#13]
Why not call it either:
- `iron-jsonp` 
- `iron-jsonp-ajax`
- `iron-ajax-jsonp`

or similar? Plain ugly with the `-library` postfix IMO

**Comment by samccone** [comment]
Hey @kristianmandrup thanks for the idea:

Unfortunately this would be a super duper downstream breaking change to any consumer, sure it is ugly but the amount of dev time this change will cost makes sticking with the name somewhat reasonable.

**Comment by atotic** [comment]
It used to be called core-shared-library. 'shared' was misleading, and the rename made its functionality clearer.
