### ISSUE TITLE
Send request mannually?

### ISSUE THREAD

**Issue by cubika** [PolymerElements/iron-jsonp-library#4]
When the `libraryUrl` is not constant, can I manually send a request by calling some methods? Just like `iron-ajax`'s `generateRequest` method?

**Comment by atotic** [comment]
No, this library has not followed iron-ajax pattern. Instead, you can create multiple iron-jsonp-libraries.
If you know all your libraries in advance, you can create library-specific loaders using jsonp-behavior. This is what google-components do.
