### ISSUE TITLE
iron-jsonp should not do initialization in ready

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/iron-jsonp-library#6]
_From @sshumaker on June 24, 2015 6:18_

the iron-jsonp behavior immediate calls this._loadLibrary() in ready(), which immediately checks libraryUrl. However, ready is called synchronously with creation, so if you want to do this:

  var api = document.createElement('iron-jsonp-library');
  api.libraryUrl = 'https://apis.google.com/js/client.js?onload=%%callback%%';
  api.notifyEvent = 'api-load';

You get an exception thrown.

Suggestion: Wrap the loadLibrary in a this.async call (so it's equivalent to 0.5 domReady), or be even smarter and observe libraryUrl changes.

_Copied from original issue: Polymer/polymer#1950_

**Comment by tjsavage** [comment]
_From @kevinpschaaf on June 24, 2015 16:52_

Agreed.

This issue tracker is for the Polymer core library, not elements built with it.  We'll get it moved to the right tracker.

**Comment by kevinwestern** [comment]
It's been a while since this was updated. We need this now, so I went ahead and sent a PR.

**Comment by atotic** [comment]
I agree that async 'loadLibrary' is a good idea. Because ironJsonPLibraryBehavior is a behavior, I need to spend some time convincing myself that all use cases are covered. I'll try make it work on Friday.

**Comment by kevinwestern** [comment]
Why would calling it async be better than observing the property? That seems to be the Polymer way and IMO a bit clearer what's going on (especially in stack traces).
