### ISSUE TITLE
Typical usage?

### ISSUE THREAD

**Issue by wbprice** [PolymerElements/iron-jsonp-library#8]
Hi,

Looking at the docs and tests it's not immediately clear how to use this component with iron-ajax.  My assumption is that the workflow is something like this:

```
1. Load a jsonp library using iron-jsonp-library
2. iron-jsonp-library loads the library, fires an event (e.g api-load)
3. After api-load is heard, the developer is free to make a request using iron-ajax
```

Which of course could be totally off base.  What patterns are people using in production code?  My attempt here: https://gist.github.com/wbprice/08462ad038387b011a23

**Comment by atotic** [comment]
I do not understan why you need to use this copmponent with iron-ajax?
The usual usage pattern is: use iron-jsonp-library to load a library, then make calls to the library once it has been loaded. Lots of google-web-components do this.

**Comment by wbprice** [comment]
Is it the case that I would use iron-jsonp-library to download a given JSONP library foo.js, and use foo.js to make network calls? And if so, I'm free to to use whatever JSONP library I choose, not necessarily Google's plusone.js?

**Comment by atotic** [comment]
yes, and yes.
